# Generated by Django 6.0.2 on 2026-09-01 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Blog Categories',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('author_name', models.CharField(default='Dr. Lachlan Hayes (BSc, MND, APD)', max_length=100)),
                ('author_role', models.CharField(default='Head of Sports Science & Clinical Nutrition', max_length=100)),
                ('excerpt', models.TextField()),
                ('content', models.TextField(help_text='Full markdown or HTML article content')),
                ('cover_image_url', models.URLField(max_length=500)),
                ('read_time_minutes', models.PositiveIntegerField(default=5)),
                ('tags', models.CharField(default='Nutrition, Muscle Building, Recovery', max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.blogcategory')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
