# Generated by Django 6.1 on 2026-09-01 07:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(default=1)),
                ('question_text', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('options', models.JSONField(default=list, help_text='Array of {id, title, desc, icon, category_slug}')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Quiz Question',
                'verbose_name_plural': 'Quiz Questions',
                'ordering': ['order', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Aussie Pure 100% Grass-Fed WPI', max_length=200)),
                ('tagline', models.CharField(default='Single-Origin Victorian Pasture Isolate', max_length=200)),
                ('hero_title', models.CharField(default='BIO-ACTIVE WHEY ISOLATE', max_length=200)),
                ('subline', models.TextField(default='Cold micro-filtered from free-roaming Gippsland dairy cows. 27.4g pure bioactive protein with zero artificial sweeteners, gums, or fillers.')),
                ('size_servings', models.CharField(default='2kg Tub • 66 Servings', max_length=100)),
                ('retail_price', models.DecimalField(decimal_places=2, default=Decimal('89.95'), max_digits=10)),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=Decimal('58.50'), max_digits=10)),
                ('image_url', models.CharField(default='/assets/hero-tub.jpg', max_length=500)),
                ('halo_gradient', models.CharField(default='from-emerald-500/30 via-gold-500/25 to-amber-500/20', max_length=200)),
                ('glow_shadow', models.CharField(default='shadow-[0_0_80px_rgba(229,169,60,0.35)]', max_length=200)),
                ('tab_label', models.CharField(default='1. Grass-Fed WPI 2kg', max_length=100)),
                ('slug', models.CharField(default='aussie-pure-grass-fed-whey-protein-isolate-2kg', max_length=200)),
                ('badge_top_value', models.CharField(default='27.4g', max_length=50)),
                ('badge_top_label', models.CharField(default='Pure Protein', max_length=100)),
                ('badge_top_sub', models.CharField(default='Per Single Serve', max_length=100)),
                ('badge_bottom_title', models.CharField(default='Victorian Dairy', max_length=100)),
                ('badge_bottom_subtitle', models.CharField(default='100% Pasture Fed', max_length=100)),
                ('badge_rating_score', models.CharField(default='4.98', max_length=20)),
                ('badge_rating_count', models.CharField(default='1,240+ Verified Reviews', max_length=100)),
                ('hotspots', models.JSONField(blank=True, default=list, help_text='Array of hotspot objects {x, y, title, detail}')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Aussie Supplements', max_length=150)),
                ('tagline', models.CharField(default='Pure Australian Nutrition • Clinical Performance', max_length=255)),
                ('announcement_text', models.CharField(default='🇦🇺 FREE EXPRESS SHIPPING ACROSS AUSTRALIA ON ORDERS OVER $100 • 100% VICTORIAN DAIRY', max_length=300)),
                ('announcement_enabled', models.BooleanField(default=True)),
                ('announcement_link', models.CharField(blank=True, default='/shop', max_length=200)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10)),
                ('default_currency', models.CharField(default='LKR', help_text='LKR, USD, or AUD', max_length=10)),
                ('lkr_multiplier', models.DecimalField(decimal_places=2, default=Decimal('200.00'), help_text='1 AUD to LKR multiplier', max_digits=10)),
                ('usd_multiplier', models.DecimalField(decimal_places=4, default=Decimal('0.6500'), help_text='1 AUD to USD multiplier', max_digits=10)),
                ('aud_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('contact_email', models.EmailField(default='support@aussiesupplements.com.au', max_length=254)),
                ('contact_phone', models.CharField(default='1300 892 877', max_length=50)),
                ('warehouse_location', models.CharField(default='Melbourne Distribution Hub, Victoria, Australia', max_length=255)),
                ('is_store_open', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='TrustPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=150)),
                ('icon_type', models.CharField(default='ShieldCheck', help_text='ShieldCheck, Leaf, Truck, Flag', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Trust Pillar',
                'verbose_name_plural': 'Trust Pillars',
                'ordering': ['order'],
            },
        ),
    ]
