# Generated by Django 6.1 on 2026-09-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='carrier',
            field=models.CharField(default='Island-Wide Express Courier (Colombo Hub)', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(default='Sri Lanka', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('STANDARD', 'Standard Island-Wide Tracked Courier'), ('EXPRESS', 'Colombo Express Priority Dispatch'), ('PALLET_FREIGHT', 'Commercial Gym Wholesale Freight')], default='STANDARD', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_gst',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
