# Generated by Django 6.0.2 on 2026-09-01 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=20.0, help_text='Default discount % off retail', max_digits=5)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WholesalePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField(default=1, help_text='Tier quantity (e.g. 1-9, 10-49, 50+)')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_prices', to='products.product')),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='wholesale.wholesaletier')),
            ],
            options={
                'ordering': ['product', 'min_quantity'],
            },
        ),
        migrations.CreateModel(
            name='WholesaleApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('abn', models.CharField(help_text='Australian Business Number (11 digits)', max_length=50)),
                ('contact_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('business_type', models.CharField(choices=[('GYM', 'Gym / Fitness Facility'), ('SUPPLEMENT_STORE', 'Supplement Store'), ('HEALTH_STORE', 'Health & Wellness Shop'), ('PHARMACY', 'Pharmacy / Chemist'), ('ONLINE_RETAILER', 'Online Retailer'), ('PERSONAL_TRAINER', 'Personal Trainer / Coach'), ('SPORTS_CLUB', 'Sports Club / Team'), ('OTHER', 'Other Commercial Entity')], default='GYM', max_length=30)),
                ('website', models.URLField(blank=True, null=True)),
                ('estimated_monthly_spend', models.CharField(default='$1,000 - $3,000', max_length=100)),
                ('interested_categories', models.CharField(default='Protein, Pre-Workout, Vitamins, Amino Acids', max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wholesale_applications', to=settings.AUTH_USER_MODEL)),
                ('assigned_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wholesale.wholesaletier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
