# Generated by Django 6.0.2 on 2026-09-01 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True)),
                ('artg_number', models.CharField(blank=True, help_text='Australian Register of Therapeutic Goods (e.g. AUST L 384920)', max_length=50, null=True)),
                ('short_description', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField()),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=100)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10)),
                ('weight_grams', models.PositiveIntegerField(default=500, help_text='Weight in grams')),
                ('size_label', models.CharField(default='1kg', help_text='e.g. 1kg, 500g, 120 Veg Caps', max_length=100)),
                ('serving_size', models.CharField(default='30g', max_length=100)),
                ('servings_per_container', models.PositiveIntegerField(default=30)),
                ('form', models.CharField(choices=[('POWDER', 'Powder'), ('CAPSULES', 'Capsules'), ('TABLETS', 'Tablets'), ('GUMMIES', 'Gummies'), ('LIQUID', 'Liquid')], default='POWDER', max_length=20)),
                ('flavour', models.CharField(blank=True, max_length=100, null=True)),
                ('dietary_tags', models.CharField(default='Australian Made, Gluten Free, Lab Tested', help_text='Comma-separated tags', max_length=255)),
                ('goal', models.CharField(default='Muscle Building, Recovery, Everyday Wellness', help_text='Primary fitness/health goal', max_length=100)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('directions_for_use', models.TextField(blank=True, null=True)),
                ('warnings', models.TextField(blank=True, null=True)),
                ('storage_info', models.CharField(default='Store in a cool, dry place below 25°C away from direct sunlight.', max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_best_seller', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='brands.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.category')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.subcategory')),
            ],
            options={
                'ordering': ['-is_featured', '-is_best_seller', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NutritionFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_size_info', models.CharField(default='30g (1 Scoop)', max_length=100)),
                ('energy_kj', models.CharField(default='495 kJ (118 Cal)', max_length=50)),
                ('protein_g', models.CharField(default='25.4 g', max_length=50)),
                ('fat_total_g', models.CharField(default='0.8 g', max_length=50)),
                ('fat_saturated_g', models.CharField(default='0.4 g', max_length=50)),
                ('carbs_total_g', models.CharField(default='1.2 g', max_length=50)),
                ('carbs_sugars_g', models.CharField(default='0.6 g', max_length=50)),
                ('sodium_mg', models.CharField(default='65 mg', max_length=50)),
                ('custom_nutrients', models.JSONField(blank=True, default=dict, help_text="e.g. {'BCAA': '5.8g', 'Glutamine': '4.2g'}")),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['-is_primary', 'order'],
            },
        ),
    ]
